### ISSUE TITLE
Improve UI for taxi stands

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#255]
Since we are faking taxi availability via the bike sharing feature we need to adjust the UI for that.

![Screenshot from 2020-06-23 14-10-40](https://user-images.githubusercontent.com/151346/85402598-3b9d3a80-b55c-11ea-81fd-ad648e1259fc.png)

Acceptance criteria

- Use the orange taxi icon in the popup and the map
- Remove everything to do with availability (but make sure that it stays for RegioRad, so it needs to be configurable)

**Comment by Beck-berry** [comment]
I switched to the icon we used previously for the taxi stands:
![Screenshot_2020-06-30_08-22-40](https://user-images.githubusercontent.com/46535522/86090773-025c5180-baab-11ea-8059-5e7e9abc184d.png)
![Screenshot_2020-06-30_08-22-52](https://user-images.githubusercontent.com/46535522/86090778-02f4e800-baab-11ea-8ad8-48e6dee10444.png)

As you can see, the second part of the popup disappeared. It must be because the `taxi` network does not have an url property: it is a condition for the display of that register part. (I tested, and added an url, then the second part appeared again.) I'll remove the remaining line too.

**Comment by Beck-berry** [comment]
Is it what you expected, right?
![Screenshot_2020-06-30_09-11-20](https://user-images.githubusercontent.com/46535522/86095080-b660db00-bab1-11ea-8f25-c004da75c3ca.png)

I also removed the availability info (for taxi stands) from the "near you" view:
![Screenshot_2020-06-30_09-16-15](https://user-images.githubusercontent.com/46535522/86095677-91b93300-bab2-11ea-8262-d1c4ed7016ab.png)
![Screenshot_2020-06-30_09-20-23](https://user-images.githubusercontent.com/46535522/86095979-f70d2400-bab2-11ea-85d8-f84ff8c4a737.png)



Would it break the backend side if I changed the network type from `citybike` to `taxi`? Is it used for the planning or something? Because as much as I see, on the UI side it only defines the correct translations - so we could add for example "cars available" text in the future and revert these "remove availability" commits. (Of course if we *want* to display availability for these at all.)

**Comment by leonardehrenfried** [comment]
I removed the URL part so that already removed the button. Good.

Not sure if we want to keep the red (x) icon. Maybe @hbruch has an idea.

You can try changing the type. It will not change the frontend and I don't know what will happen to the frontend.

**Comment by Beck-berry** [comment]
Changing the type to something (for example, "taxi") that is not handled will fall back to the type `citybike`. But I think as at many places there is a "decision" between citybike and scooter, we could update these parts and also add `taxi` (and anything else we want) with the correct texts.

**Comment by Beck-berry** [comment]
For example:
![Screenshot_2020-06-30_10-02-02](https://user-images.githubusercontent.com/46535522/86100412-127b2d80-bab9-11ea-8c8b-9a34f9bd7a3d.png)

**Comment by leonardehrenfried** [comment]
I like it.
