### ISSUE TITLE
Fix broken layout when there are many legs

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#275]
![Screenshot from 2020-07-16 09-08-56](https://user-images.githubusercontent.com/151346/87638451-15764f00-c744-11ea-945b-15941545e2f5.png)

The itinerary in the left hand panel overflows its size when there are many legs. Not sure if it has anything to do with cycling since we had trips with many legs before.

Also check if this problem exists in Helsinki.

Link: https://tinyurl.com/y8rf22ag

**Comment by meromisi** [comment]
A long time ago in an office far from Herrenberg, we made `walk` transit mode a `leg` so it is displayed as many times in the itinerary overview as it appears in the itinerary. In some cases, when there are more than 5 legs in an itinerary, it breaks the UI because there's no enough place to display. Here's an example how 2 similar itineraries looks like in statnavi and in HSL.

Stadtnavi:
![image](https://user-images.githubusercontent.com/54352878/87915699-c8131e00-ca72-11ea-840a-4612e8101c67.png)

HSL:
![image](https://user-images.githubusercontent.com/54352878/87915810-e6791980-ca72-11ea-974d-ecf102e62d1c.png)

Both of them has about 500m of walking just HSL only displays it under the amount of time of the trip. 
One possible solution could be to reverse the changes and display the itinerary as HSL does, WDYT?

**Comment by leonardehrenfried** [comment]
Personally I like it.

**Comment by meromisi** [comment]
Me too, because walking takes only minority of the trip but it is displayed equally as the other transports, additionally walking always displayed on the right.

**Comment by leonardehrenfried** [comment]
That also explains why I could not reproduce this on HSL.

**Comment by Beck-berry** [comment]
We introduced a `renderAlwaysNonTransitLegs` prop back then, which is `true` to render walking into the summary too. If we'd like to fix this UI problem fast, we can set this prop to `false` easily.

**Comment by leonardehrenfried** [comment]
Holger would like the walking legs to stay.

For this reason you need to get your head around the flex box model and how to shrink the legs when there are many of them. You probably need to read up on how flex box works. Don't worry if it takes a long time.
