### ISSUE TITLE
Remove warnings/errors from console

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#278]
We currently have a number of errors that show up in the console. I'm pretty sure that they are harmless but let's fix them so we can spot the real problems.

![Screenshot from 2020-07-21 10-35-42](https://user-images.githubusercontent.com/151346/88032303-10e3d900-cb3e-11ea-92cf-68d568423317.png)
![Screenshot_2020-07-24_10-51-48](https://user-images.githubusercontent.com/46535522/88375568-18a0b900-cd9c-11ea-85dc-edd4c33236af.png)

**Comment by Beck-berry** [comment]
Got from [previous comment](https://github.com/stadtnavi/digitransit-ui/issues/276#issuecomment-661092767):
![error](https://user-images.githubusercontent.com/151346/87952481-290a1880-caaa-11ea-95ff-3c054bfa4d3d.png)

It seems to me that when we update the `useCarParkAvailabilityInformation` param in the CarLeg, the parent  SummaryPage (where it originally fetches the data) still has the previous value and this might cause the difference. Is this possible?
[This is kind of the closest of the SO issues](https://stackoverflow.com/questions/37866342/relay-fragment-variables) I could find but this is still hard for me to implement to our case.

I removed the query params from SummaryPlanContainer in ea9f088 since they had no effect on the research (and the error occurs also with and without that) but is it possible that the error still comes from there? (There is a `${SummaryPlanContainer.getFragment('plan')}` line inside the query of the SummaryPage.)

I don't really have any other good ideas.

**Comment by leonardehrenfried** [comment]
Is it possible that the problem might be that useCarAvail... is not in the props of the component? Are the other routing parameters props?

**Comment by Beck-berry** [comment]
Well, some of them. Adding the `useCarParkAvailabilityInformation` as a prop will cause an error (at least for eslint) since it won't be used and  - more importantly - also won't fix the previous warning.

**Comment by Beck-berry** [comment]
![Screenshot from 2020-07-21 10-35-42](https://user-images.githubusercontent.com/151346/88032303-10e3d900-cb3e-11ea-92cf-68d568423317.png)
`searchTime` comes from a Relay query which is expected to be an object, but got a number.
This seems to me a Relay "issue" since Relay wants everything to be the type of object. According to the [source code](http://www.bvbcode.com/code/cfywrk5a-2589108) I found the direct source of this warning:
```js
// handle invalid prop values using a warning at first.
if (typeof propValue !== 'object') {
  warning(
    false,
    'RelayContainer: Expected prop `%s` supplied to `%s` to be an ' +
    'object, got `%s`.',
     fragmentName,
     componentName,
     propValue
   );
   fragmentPointers[fragmentName] = null;
   return;
 }
```
Thus HSL has this warning too. (Checked locally.)
