### ISSUE TITLE
Map on mobile start view 

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#343]
Currently the mobile start page is pretty blank. Stadtnavi should display a map very prominently. As most trips start at the user's current location, only entering the destination should be required. Search results should be displayed on a bottom sheet pane which can be enlarged/minimized using swipe on mobile.

## Design idea
![image9](https://user-images.githubusercontent.com/151346/115221092-987c6980-a109-11eb-9c44-98643865c5c6.png)

**Comment by Denis306** [comment]
@hbruch : Do we want a pop up for the mobile start view that prompts the user to download the map? 
Something like: "You can download the Stadtnavi App!" 
And if you dont want to you can simply close it.

**Comment by andreashelms** [comment]
![image](https://user-images.githubusercontent.com/21622725/119496757-1c0e2380-bd64-11eb-8850-1d1275d53c57.png)
![image](https://user-images.githubusercontent.com/21622725/119496799-26302200-bd64-11eb-835e-8e153ab43818.png)

@leonardehrenfried There is a built-in option to enable map on mobile. It shows the map on top of the start/destination input fields. The input fields can even be swiped down so that map is nearly fullscreen.
Is it okay to just use this view or should we still implement a custom map on mobile start view?

**Comment by leonardehrenfried** [comment]
What a fantastic find!

Please enable this and we deploy it - we can then evaluate if is good enough.

**Comment by leonardehrenfried** [comment]
And with this in place we can concentrate on the panels: https://github.com/stadtnavi/digitransit-ui/issues/344

**Comment by samia-roubaa** [comment]
QA cycle done
