### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#386]
There are a couple of German translations missing

<img width="442" alt="grafik" src="https://user-images.githubusercontent.com/2187389/117210861-8896a200-adf8-11eb-8188-26476a4f13e0.png">

<img width="463" alt="grafik" src="https://user-images.githubusercontent.com/2187389/117210906-9c420880-adf8-11eb-94bd-02607b39e575.png">

<img width="402" alt="grafik" src="https://user-images.githubusercontent.com/2187389/117210961-b24fc900-adf8-11eb-8059-2e3b1772f527.png">

**Comment by hbruch** [comment]
And English translations as well

<img width="452" alt="grafik" src="https://user-images.githubusercontent.com/2187389/117211263-0f4b7f00-adf9-11eb-9e72-f7db32760376.png">

**Comment by leonardehrenfried** [comment]
These translations should be contributed upstream.

**Comment by aaronyamil** [comment]
@leonardehrenfried The translations have many inconsistencies.
We have 7 languages, do I need to update all 7 languages or only German and English?

**Comment by aaronyamil** [comment]
Ok thanks!. I am going to work in both languages.

**Comment by aaronyamil** [comment]
Hi @leonardehrenfried , I created a PR with the fix : https://github.com/stadtnavi/digitransit-ui/pull/432

Before the update:
1. German: 577 records
2. English: 621 records 

After the update:
1. 644 records in both German and English. I compared one by one and translated the missing ones. I use google translate.
2. Both are arranged alphabetically.
3. I formatted all file this way:  "field": "value" . Because many records had a different formats.
