### ISSUE TITLE
Fix styling and colours of bike rental legs

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#446]
Since yesterday we have bike rentals back in DT2, however the styling doesn't match DT1.

![Screenshot from 2021-05-12 09-33-42](https://user-images.githubusercontent.com/151346/117936572-4c39d900-b305-11eb-8685-8c2f23a16ca2.png)

Note: in order to have a bike rental leg you need to plan a search from Ehningen to Kuppingen (for example), deactivate the bus and activate bikr rental in the settings panel.

Things to fix
- make polyline blue even when combined with train
- remove the station id ("7bd6d9cb-509b-4378-83db-cebb44ee1f6f") from the left hand panel when viewing an individual itinerary
- make the bike leg (after train) also blue and add the badge about how many bikes are available when viewing the list of routes in the left hand panel:
![Screenshot from 2021-05-12 09-37-38](https://user-images.githubusercontent.com/151346/117937258-10ebda00-b306-11eb-8a69-13cafd0a4415.png)

**Comment by aaronyamil** [comment]
Status:

1. make polyline blue even when combined with train **(inprogress)**
2. remove the station id ("7bd6d9cb-509b-4378-83db-cebb44ee1f6f") from the left hand panel when viewing an individual itinerary  **(done)**
3. make the bike leg (after train) also blue and add the badge about how many bikes are available when viewing the list of routes in the left hand panel.   **(todo)**

**Comment by aaronyamil** [comment]
Hi @leonardehrenfried

**Comment by aaronyamil** [comment]
Hi @leonardehrenfried 

This ticket has 3 subtasks: 

1. make polyline blue even when combined with train _**(It is a backend issue because the rentedBike arrives FALSE )**_
2. remove the station id ("7bd6d9cb-509b-4378-83db-cebb44ee1f6f") from the left hand panel when viewing an individual itinerary _**( I fixed this, I removed the station Id. Can i upload this change? )**_
3. make the bike leg (after train) also blue and add the badge about how many bikes are available when viewing the list of routes in the left hand panel. **_(is this a backend issue too?? )_**

**Comment by leonardehrenfried** [comment]
Yes, both are backend issues. It's being tracked here: https://github.com/mfdz/OpenTripPlanner/issues/72

Lets keep this ticket open until that one is resolved and re-evaluate.

**Comment by aaronyamil** [comment]
Sure, no problem.
thanks

**Comment by samia-roubaa** [comment]
QA cycle done.
