### ISSUE TITLE
User Feedback: Car should be parked in a nearer parking and then transit

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/digitransit-ui#541]
https://herrenberg.beta.stadtnavi.eu/reiseplan/Kuppingen%2C%2071083%20Herrenberg%3A%3A48.610752%2C8.8431229/Universit%C3%A4t%20Stuttgart%2C%20Schlo%C3%9Fstra%C3%9Fe%2C%2070176%20Stuttgart%3A%3A48.7453828%2C9.103267538773398/parkAndRide/?time=1622558694

Go to the route Park and ride
Current behavior: first route shown is Car + Park + Walk (47 min)
Feedback came from Julian, he thinks that the car should have been parked even earlier in Nufringen and then take the train from there. This route is actually shown but as the 4th route. Can it be the first?

Feedback number: 219

**Comment by leonardehrenfried** [comment]
Since this has already been reported at #529 I had already worked on this.

It's fixed on dev: https://dev.stadtnavi.eu/reiseplan/Kuppingen%2C%2071083%20Herrenberg%3A%3A48.610752%2C8.8431229/Universit%C3%A4t%20Stuttgart%2C%20Schlo%C3%9Fstra%C3%9Fe%2C%2070176%20Stuttgart%3A%3A48.7453828%2C9.103267538773398/parkAndRide/?time=1622568319

I will roll it out to beta soon.
