### ISSUE TITLE
No title in station view

### ISSUE THREAD

**Issue by leonardehrenfried** [stadtnavi/digitransit-ui#629]
Upstream has them

![Screenshot from 2021-06-14 13-26-43](https://user-images.githubusercontent.com/151346/121885385-6572e280-cd14-11eb-8e38-9fee7188ad15.png)

But we don't
![Screenshot from 2021-06-14 13-26-10](https://user-images.githubusercontent.com/151346/121885393-67d53c80-cd14-11eb-9349-72a4dc646685.png)

Please investigate.

**Comment by Beck-berry** [comment]
It must be because the `CardHeader` component would use the `stop.name` to produce a title there but we do not get the data, however the graphQL query contains it (`StopCardHeaderContainer` component).

![image](https://user-images.githubusercontent.com/46535522/122094431-79017480-ce0c-11eb-8aa4-ed6ffa5697cf.png)

Is it surely sent from the backend?

**Comment by leonardehrenfried** [comment]
![Screenshot from 2021-06-15 19-26-13](https://user-images.githubusercontent.com/151346/122097656-32ae1480-ce10-11eb-89dc-8a19bf3bb93a.png)

I can see it but it's probably not moved to the correct place.

**Comment by leonardehrenfried** [comment]
Screenshot updated.
