### ISSUE TITLE
Feedback User 237: Route is too long 

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/digitransit-ui#644]
Origin: Am Joachimsberg 17, Herrenberg
Destination: Schlossberg 1, Herrenberg

When comparing the route of Google maps with Stadtnavi, the Stadtnavi route takes 11mins longer. 

![image](https://user-images.githubusercontent.com/84382750/122178576-fbc71580-ce86-11eb-9b89-66d4c7a08e74.png)

![image](https://user-images.githubusercontent.com/84382750/122178861-421c7480-ce87-11eb-9340-e3a671baea6a.png)

**Comment by leonardehrenfried** [comment]
The two results aren't quite the same here. Google goes to the address "Schlossberg 1" but the stadtnavi screenshot shows going up the mountain to "Schlossberg".

If you correct the destination you get a much more reasonable 14 minutes:

![Screenshot from 2021-06-16 10-23-29](https://user-images.githubusercontent.com/151346/122184845-e8b74400-ce8c-11eb-8d0b-c1645aa7afaa.png)

https://herrenberg.stadtnavi.de/reiseplan/Am%20Joachimsberg%2017%2C%2071083%20Herrenberg%3A%3A48.60063315%2C8.875706733872033/Evangelisches%20Dekanat%2C%20Schlossberg%201%2C%2071083%20Herrenberg%3A%3A48.59646807856256%2C8.872581124305727?time=1623831677

Why does the route start at Marderweg?

It's because the house is a tiny bit closer to it than to Am Joachimsberg: https://www.openstreetmap.org/way/33814364

What we could do here is to add a small path from the street to the house which our routing algorithm could find.

That would make the route look like this: https://herrenberg.stadtnavi.de/reiseplan/Am%20Joachimsberg%2017%2C%2071083%20Herrenberg%3A%3A48.60050886267065%2C8.875858783721926/Evangelisches%20Dekanat%2C%20Schlossberg%201%2C%2071083%20Herrenberg%3A%3A48.596475174164745%2C8.87251138687134?time=1623831677

Why doesn't it take the route via the mountain?

Our calculation says that it's actually not a lot quicker to do so because of the incline of the hill but perhaps we are wrong. Maybe the user could indicate if going up the hill is preferable.

**Comment by leonardehrenfried** [comment]
I've taken the liberty to just add a footpath leading from Am Joachimsberg to the house. This means that the route from that address will start on that part of the house.

![Screenshot from 2021-06-16 10-48-29](https://user-images.githubusercontent.com/151346/122188596-66308380-ce90-11eb-88df-66b0d45e840e.png)

Can you ask the user to verify that this is a pedestrian path and not actually meant for cars. It's not quite clear from the areal photo.

**Comment by leonardehrenfried** [comment]
After having changed the OSM data, we get the following result now:

![Screenshot from 2021-06-24 09-06-05](https://user-images.githubusercontent.com/151346/123218474-0e1b0200-d4cc-11eb-9873-769a15a90aee.png)

Our algorithm says that it takes 12 minutes but of course this is dependent on your personal fitness.

I also think that the Google route to approach the destination is not correct. It's a bit hard to say if you can enter the building from the north east but from the areal photo it doesn't look like you can.

![Screenshot from 2021-06-24 09-14-18](https://user-images.githubusercontent.com/151346/123219001-b0d38080-d4cc-11eb-9791-dee98cc2cc82.png)

I think that approaching from the west, as stadtnavi does, is correct.

**Comment by leonardehrenfried** [comment]
However, if the user that reported this has better local knowledge we would be happy to update the underlying map data.

**Comment by MartinH-open** [comment]
To me the footpath for this example looks very good. Thanks!
(So OSM changes go into StadtNavi over night. We need to document such update cycles somewhere for StadtNavi instance Herrenberg. Holger explained it once - but it is not easy to find .. on Github?  We should have a Repository for the Herrenberg Instance to hold all such local information specific for Herrenberg.)

BTW - the same route for using car only returns : "Your search returned only walking routes."
walking is fine for that distance - but I'm sure there would be ways to go by car too. 
Even with all public transports enabled the search returns: "Your search returned only walking and cycling routes."
(And wheelchair options then leads to: Unfortunately, no route suggestions were found.)
