### ISSUE TITLE
Feedback User 269: shortest car ride should be shown first in P+R mode

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/digitransit-ui#670]
current behavior: when the user chooses P+R, the longest car rides are shown first in the results. 
expected behavior: the shortest car rides should be shown first. 

Route used in the screenshot: Kuppingen-Stuttgart

![image](https://user-images.githubusercontent.com/84382750/122674810-019a5f00-d1d7-11eb-8338-d4b1ee5e91b3.png)

**Comment by hbruch** [comment]
I object. Currently, we order trips by their start time (for departure time searches) or arrival time (for arrival time searches). IMO this is more intuitive than shuffling the trips by some hard to grasp criteria. To be honest, in my eyes, both displayed options make sense: the later ones for people wanting to avoid driving, the first ones for people who want to avoid Stuttgart inner city. 

Could you explain, why you see this as a bug?

**Comment by MartinH-open** [comment]
In general, the sorting of the proposals in quite unclear - and not displayed somehow.
I assume some "automatic" sorting is implemented somehow.
Often sorting is by departure time which could be reasonable.

> (EDIT: Now I read the explaination above given by @hbruch. Thanks! 
> Perhaps the current implicit sorting could be displayed somehow: e.g. bold font for starting times or for arrival times.
> Or even a button to select the sorting by preference)

If more than 3 proposals are displayed StadtNavi could display some sorting option.
by departure time, by arrival time, or by duration of travel, or by cost of travel, or by number of modal changes (which might be secondary criteria unless you are handicapped)

**Comment by sara-georgy** [comment]
@hbruch the issue was reported in the support feedback. It was mentioned that no car rides longer than 20mins should be displayed in the first route suggestions.

**Comment by hbruch** [comment]
As I said, I don't see a bug in the results cited above. @MartinH-open Could you give specific examples where you think sorting is unclear? 

As I mentioned, ordering should be done on either departure or arrival time, depending on search mode. IMO this is the most clear sorting order we can provide. If you opt for other, user definable sorting criteria, I suggest you open a feature request.

**Comment by MartinH-open** [comment]
@hbruch - this Issue request is not mine. 
Thanks, for explaining that "either departure or arrival time, depending on search mode" is done. That is fine. 
(Somehow I was not sure because often I specify arrival time and did not notice this changes the sorting too.)
The action buttons "^Früher" or "v Später" indicate already that sorting is by time. Fine !
If we want to clarify the sorting a bit perhaps we should display "^Früher starten" or "^Früher ankommen" and "v Später starten" or "v Später ankommen" - depending on the search mode. (not sure this is a small valid feature request)

And I agree that in the example the given proposals and their sorting makes perfect sense !
If certain proposals should be dropped (no car rides for longer than 20 minutes) then this should be some filter setting preference, but not defined by sorting.

After understanding the sorting now - I think it makes perfect sense given the current constraints. 
If we knew other cost factors for the trip (e.g. ticket prices, CO2 savings) we could offer a preference ordering by such factors in addition. Travel duration might be another factor and number of modal switches. (but these could be ruled by a filter too).

**Comment by hbruch** [comment]
@sara-georgy I suggest closing this issue, as sort order works as intended

**Comment by sara-georgy** [comment]
okay, I will close it.

**Comment by MartinH-open** [comment]
I'm fine with closing this too. 
The given explanation helps. Not sure how relevant and obvious this is for new users.
Anyhow, as written: The action buttons "^Früher" or "v Später" indicate already that sorting is by time. Fine !
If we want to clarify the sorting a bit perhaps we should display "^Früher starten" or "^Früher ankommen" and "v Später starten" or "v Später ankommen" - depending on the search mode. 
(Perhaps - at a later time I might bring up this as small feature request)
