### ISSUE TITLE
Feedback from Ansgar: wrong parking place indicator

### ISSUE THREAD

**Issue by sara-georgy** [stadtnavi/digitransit-ui#678]
The "Unterer Graben" parking place has the orange indicator although 12 out of 39 parking spaces are still free. 

![image](https://user-images.githubusercontent.com/84382750/122879686-7a193100-d339-11eb-81ac-feb1422ddaaa.png)

**Comment by leonardehrenfried** [comment]
To the frontend devs: I think the problem is, that the user has clicked on an URL which has the free spaces encoded in it but the information is out of date.

We now have a proper API in the backend to fetch information about a parking lot with a GraphQL call.

Can we please pass the ID of the parking lot in the URL instead and fetch the information with the following GraphQL query?

```
query parking {
  vehicleParking(id: "OSM:OSMWay/39040154") {
    vehicleParkingId
    name
    lon
    lat
    capacity {
      carSpaces
      bicycleSpaces
      wheelchairAccessibleCarSpaces
    }
    availability {
      carSpaces
      bicycleSpaces
      wheelchairAccessibleCarSpaces
    }
    imageUrl
    tags
    anyCarPlaces
  }
}
```

Basically, it should work just like a sharing station: https://herrenberg.stadtnavi.de/fahrradstationen/7bd6d9cb-509b-4378-83db-cebb44ee1f6f

**Comment by Beck-berry** [comment]
Can the backend give back the followings?
* lotType
* note
* openingHours
* detailsUrl
* state

**Comment by leonardehrenfried** [comment]
Yes, they are all there.

**Comment by leonardehrenfried** [comment]
- `lotType` and `state` are in the tags
- `note` and `detailsUrl` is a property
- `openingHours` is indeed missing! I will fix that!

**Comment by Beck-berry** [comment]
`feature/#678-parking_place_indicator`  branch is pushed, theoretically the link and the props will work fine, the two places marked with TODO are not final, and the schema still has to be extended

**Comment by leonardehrenfried** [comment]
The full query is something like this:

```
query parking {
  vehicleParking(id: "OSM:OSMWay/39040154") {
    vehicleParkingId
    name
    lon
    lat
    capacity {
      carSpaces
      bicycleSpaces
      wheelchairAccessibleCarSpaces
    }
    availability {
      carSpaces
      bicycleSpaces
      wheelchairAccessibleCarSpaces
    }
    imageUrl
    tags
    anyCarPlaces
    detailsUrl
    note
    openingHours
  }
}
```
