### ISSUE TITLE
Date range for roadworks has wrong locale

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/digitransit-ui#698]
Though in German locale, the date range for roadworks is indicated in English locale

<img width="764" alt="image" src="https://user-images.githubusercontent.com/2187389/123261226-c362af80-d4f6-11eb-8cec-ba872c9df9af.png">

**Comment by MartinH-open** [comment]
For me this location looks likes this when displaying in DE Mode (perhaps someone fiddling on the data right now)
![image](https://user-images.githubusercontent.com/1383111/123262193-e8a3ed80-d4f7-11eb-92b6-272656a7a8dd.png)

In EN mode I see this - even worse - because of missing English translation 
(perhaps translation can be automated - if languages are missing - or out-sourced to the crowd entering : "Renewal on the ceiling")
![image](https://user-images.githubusercontent.com/1383111/123262571-4e907500-d4f8-11eb-952f-77992bdd4600.png)

**Comment by MartinH-open** [comment]
BTW - I think StadtNavi gives too much focus on what is  NOT working (Baustellen) - displayed in bold red solid lines
![image](https://user-images.githubusercontent.com/1383111/123264321-3588c380-d4fa-11eb-9d72-b08abb0746f6.png)

instead of displaying them only when relevant for the proposed routes (by car, bus, or bike). Or display in a more subtle way with some transparent dotted thin line only.
Today BW is covered by red bold lines and circle indicating the many issues:
![image](https://user-images.githubusercontent.com/1383111/123264832-b21ba200-d4fa-11eb-8334-44b1b7c17366.png)

**Comment by MartinH-open** [comment]
OT: Perhaps instead StadtNavi should display more in a positive manner the roads and areas in greenish colors that have been served by means of public transport in the last 2h or 12h in shades of how man people where transported that way.
This would tell newcomers right away which connections and areas a well served by public transport.  (End of feature request)

**Comment by andreashelms** [comment]
> Though in German locale, the date range for roadworks is indicated in English locale
> 
> <img alt="image" width="764" src="https://user-images.githubusercontent.com/2187389/123261226-c362af80-d4f6-11eb-8cec-ba872c9df9af.png">

Can't reproduce this issue. Looks good to me.
![image](https://user-images.githubusercontent.com/21622725/123609220-c4018b80-d7ff-11eb-967e-06cee0ef5a4b.png)
