### ISSUE TITLE
Ruftaxi unexpected behavior

### ISSUE THREAD

**Issue by ahmed-nawar** [stadtnavi/digitransit-ui#715]
https://herrenberg.beta.stadtnavi.eu/reiseplan/Aerospace%20Lab%20e.V.%2C%20Berliner%20Stra%C3%9Fe%201%2C%2071083%20Herrenberg%3A%3A48.59471898222628%2C8.85652542114258/Seestra%C3%9Fe%2017%2C%2071154%20Nufringen%3A%3A48.6200873639028%2C8.892831802368166/?time=1624829400

Following this comment https://github.com/stadtnavi/digitransit-ui/issues/590#issuecomment-865920069 from @leonardehrenfried 
I tried several scenarios to validate the difference between the "to-door-service" and "regular-bus". This route is confusing because the ruftaxi appears in the suggestions normally and NO ruftaxi tile appears.
Also when you click on the ruftaxi itinerary the message for the extra fees is shown.

Expected behavior: A normal bus appears and an extra walking leg to reach destination in the suggested itineraries (The extra fees message should not be shown) and a ruftaxi icon appear where you can click it and the route with the extra fees appears (With the RT).

![image](https://user-images.githubusercontent.com/84456072/123547446-1b9cea00-d761-11eb-9045-50d8ab0fcbbc.png)

**Comment by leonardehrenfried** [comment]
You're right that it's confusing but after a lot of experimenting, we arrived at this solution as the least confusing.

We do the following:

- We treat a Ruftaxi as a normal bus - which it is, but you have to call ahead of time
- On top of this, if your destination is within 300 meters of a bus stop of that particular "bus" line then the tab for the Ruftaxi appears. Because of all these limitations it's actually not easy to make the tab appear, even for me.

In your case there just isn't a line that goes this way that is able to drop you off at directly at the destination. If you're looking for a combination of train Ruftaxi, your destination is too close to the station where just walking is probably easier.

**Comment by MartinH-open** [comment]
@leonardehrenfried - thanks for explaining a bit. Still not very clear for a normal user. (I spent hours to understand StadtNavi Ruftaxi concept)
Why to "hide" the Ruftaxi on the far most tab as the last option?
Why not treat it like an additional bus connection if this is available for the destination?
Example: here the RT779 ist provided as a regular service with the regular bus stop (8 min).
![image](https://user-images.githubusercontent.com/1383111/123558231-6e909480-d795-11eb-95a2-0fa11a2c3311.png)

In addition the Ruftaxi tab is displayed which uses the same route with home-service (6 min).
![image](https://user-images.githubusercontent.com/1383111/123558303-d941d000-d795-11eb-8993-5cb5f27ab743.png)
Such alternative route could just be presented next to / below the regular route above. Users decide which to select.

**Comment by MartinH-open** [comment]
And BTW - the displayed hint does not fit to such situations where besides foot and bike also Ruftaxi and Car are alternatives:
![image](https://user-images.githubusercontent.com/1383111/123558508-e612f380-d796-11eb-9937-fdb8cd61ab19.png)

**Comment by MartinH-open** [comment]
With every mode deselected (no bus, no bike, no car, avoid walking) and walking speed = low I get this regular Ruftaxi line as a proposal which includes some 550m of walking.
![image](https://user-images.githubusercontent.com/1383111/123558711-02636000-d798-11eb-8ecd-09d0d4600b29.png)

If I change the walking speed to normal I get a Ruftaxi proposal on the tab with "home-serving" which takes me almost to my destination with a remaining 100 m to walk:
![image](https://user-images.githubusercontent.com/1383111/123558778-58d09e80-d798-11eb-959d-1785076df106.png)

**Comment by ahmed-nawar** [comment]
@MartinH-open I just tried it. It seems that the walking speed is a deciding factor for which the RT tile appears. Confusing IMHO.

**Comment by ahmed-nawar** [comment]
> You're right that it's confusing but after a lot of experimenting, we arrived at this solution as the least confusing.
> 
> We do the following:
> 
> * We treat a Ruftaxi as a normal bus - which it is, but you have to call ahead of time
> * On top of this, if your destination is within 300 meters of a bus stop of that particular "bus" line then the tab for the Ruftaxi appears. Because of all these limitations it's actually not easy to make the tab appear, even for me.
> 
> In your case there just isn't a line that goes this way that is able to drop you off at directly at the destination. If you're looking for a combination of train Ruftaxi, your destination is too close to the station where just walking is probably easier.

The RT tile didn't show so I assumed that there isn't a line that can drop me off directly at the destination like you just said. But the confusing part is that when I clicked on the itinerary details, a message with extra fees shows. I think you mentioned to me before that this message only shows if the RT will drop the user directly at the destination.

**Comment by leonardehrenfried** [comment]
These are all good points, @MartinH-open and @ahmed-nawar .

I was not quite precise enough: we consider a route "to door delivery" if there is less than two minutes walking at the end of the route. That's why - if you are at the border of one of those 300m zones - you might see the result (or not) if you change the walking speed. If this continues to be a source for confusion we can change the check to a fixed number of meters (rather than minutes) instead.
