### ISSUE TITLE
Reset origin and destination fields

### ISSUE THREAD

**Issue by nghanem-poet-egypt** [stadtnavi/digitransit-ui#724]
This issue has the following triggers- after I have entered Origin and Destination and a certain route is shown I can: 
- [x] **1. click on Stadtnavi Logo**
-- Current behavior: the route disapears but the user inputs stay the same
-- Expected behavior: both origin and destination should be deleted and the initial state of the map should be loaded
- [x] **2.  click on Startseite in Menu**
-- Current behavior: the route disapears but the user inputs stay the same
-- Expected behavior: both origin and destination should be deleted and the initial state of the map should be loaded
- [ ]  **3.  click on [x] button inside one of the text fields, while the other one is filled**
-- Current behavior: nothing happens, the text field is emptied and the drop-down is opened, but when I click outside of the text field the value retuns in the text field
-- Expecte behavior: the text field should be emptied and the map should zoom to the adress that is written in the other text field as if I only searched for this adress 
-- If both fields are being emptied through the [x] then they should both stay empty. The map should return to its original state if that's possible, if not then it should stay as is but the fields should be empty. 

In all cases the settings should not be reset, they should stay the same only the origin and destiantion fields should be reset. 

@andreashelms Please ignore my next scentece, no it's not working on beta. It is only working when I've disabled all modes except for transit and there is no walking mode found (but this happens very rare). _- IGNORE I've seen that the first two issues were already solved on Beta, have you worked on them is there another github issue for that?-_

**Comment by MartinH-open** [comment]
in general the map focus is reset to Herrenberg city far to often.
It should be reset only for some above few exceptions (Home button, Startpage).
Else if you are defining the origin and destination the map should just continue to show the current map portion instead of zooming back to home position Herrenberg. Eg. If you plan a route from Kuppingen to Gärtringen you don't want to focus the map to the center of Herrenberg in between.

**Comment by andreashelms** [comment]
Actually implementing the clear origin/destination fields feature when clicking the [x] button (Point 3) isn't that easy, because the code of two sub-packages within repository (`digitransit-component-autosuggest` and `digitransit-component-autosuggest-panel`) needs to be changed. I spend some time on investigating how to implement that, but decided two leave that feature out for now because the effort would be way bigger than the use of that feature.
