### ISSUE TITLE
Question: Interested in 'config.*.js' documentation?

### ISSUE THREAD

**Issue by dancesWithCycles** [stadtnavi/digitransit-ui#757]
Hi folks,
for people new to [digitransit-ui](https://github.com/HSLdevcom/digitransit-ui), learning the `config.*.js` files might have a steep learning curve. That is why I started a [branch/PR](https://github.com/dancesWithCycles/digitransit-ui/blob/config/docs/Configuration.md) describing the variables in those `config.*.js` files.

Please let me know if I shall make those commits also available as PR to the [stadtnavi](https://github.com/stadtnavi/digitransit-ui) repo.

At the moment, I am stumbling about the usage of the following variables and the consequences when changing the respective values. I can go on with trial and error and searching through the code to figure this out. However, I appreciate any hint pointing me in the right direction. Cheers!
```
    searchParams: {
        'boundary.rect.min_lat': 48.34164,
        'boundary.rect.max_lat': 48.97661,
        'boundary.rect.min_lon': 9.95635,
        'boundary.rect.max_lon': 8.530883,
        'focus.point.lat': 48.5957,
        'focus.point.lon': 8.8675
    },

    areaPolygon: [
        [minLon, minLat],
        [minLon, maxLat],
        [maxLon, maxLat],
        [maxLon, minLat],
    ],

    defaultEndpoint: {
        lat: 48.5942066,
        lon: 8.8644041,
    },
```

**Comment by hbruch** [comment]
Hi @dancesWithCycles!

Thanks for your input and questions. We are always happy with additional documentation. Most helpful would be to have it upstream with HSLdevcom/digitransit-ui (if they do not relate to specific stadtnavi extensions). Would you like to request a merge there? 

Regarding your questions above:
searchParams are used by [geocoding queries](https://github.com/stadtnavi/digitransit-ui/blob/next/app/util/oldParamParser.js#L37-L64). Only results in boundary.rect are returned, with matches close to focus.point receiving a higher relevance.

areaPolygon is the area this instance is expected to return results for, if origin/destination are inside this area. If either origin or destination are outside this area, an [error message](https://github.com/stadtnavi/digitransit-ui/blob/next/app/component/ItinerarySummaryListContainer.js#L210-L215) is displayed to the user.

defaultEndpoint specifies the default map center the map is zoomed to when not specified otherwise.

**Comment by dancesWithCycles** [comment]
Hi @hbruch ,
Thank you so much for your answer. I would be happy to request a merge upstream. Cheers!
